tasks/models.py
import os
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

import constants as co


def ValidateTerms(value):
  if not value:
    raise ValidationError('Please accept terms.')


class Categories(models.Model):
  pid = models.ForeignKey('self', blank=True, null=True)
  name = models.CharField(max_length=co.MAX_STRING_LEN)

  def __str__(self):
    return self.name

  class Meta:
    db_table = 'categories'


def get_attach_path(instance, filename):
  return os.path.join(instance.owner.username, 'attach', filename)


class Task(models.Model):
  paper_title = models.CharField(max_length=co.TITLE_MAX_LEN)
  discipline = models.CharField(choices=co.DISCIPLINES, max_length=co.TITLE_MAX_LEN, default=co.DISCIPLINES[0])
  assigment = models.CharField(choices=co.ASSIGMENTS, max_length=co.TITLE_MAX_LEN, default=co.ASSIGMENTS[0])
  level = models.CharField(choices=co.LEVELS, max_length=co.TITLE_MAX_LEN, default=co.LEVELS[0])
  urgency = models.SmallIntegerField(choices=co.URGENCY, default=co.URGENCY[0])
  spacing = models.SmallIntegerField(choices=co.SPACING, default=co.SPACING[0])
  page_number = models.SmallIntegerField()
  style = models.SmallIntegerField(choices=co.STYLES, default=co.STYLES[0])
  source_number = models.SmallIntegerField()
  instructions = models.TextField(blank=True, null=True)
  attach = models.FileField(upload_to=get_attach_path, blank=True, null=True)
  discount = models.CharField(max_length=co.TITLE_MAX_LEN, blank=True, null=True)
  accept_terms = models.BooleanField(validators=[ValidateTerms])
  #######################################
  ttype = models.SmallIntegerField(choices=co.TASK_TYPES, blank=True,
                                   default=co.TYPE_TASK)
  access_level = models.SmallIntegerField(choices=co.ACCESS_LEVELS, blank=True,
                                          default=co.PUBLIC_ACCESS)
  owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True,
                            related_name='owner')
  assignee = models.ForeignKey(User, null=True, blank=True,
                               related_name='assignee')
  created = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)
  completed = models.DateTimeField(null=True, blank=True)
  status = models.SmallIntegerField(choices=co.TASK_STATUSES, blank=True,
                                    default=co.NOT_ASSIGNED)

  def __str__(self):
    return self.title

  @models.permalink
  def get_absolute_url(self):
    return  ('task_view', (), {'pk': self.id})
  to_link = get_absolute_url

  class Meta:
    db_table = 'tasks'

templates/tasks/admin-tasks.html
{% load i18n render_status %}
<thead>
    <tr>
        <!--
        id
        order name
        ass type
        status
        marks *****
        site (url)
        owner
        admin
        writer
        editor
        Local time
        Created
        Urgency
        Full Deadline
        Writer's deadline
        Updated
        Order type priv/public
        in review 1/0
        Discount (%)
        Payment status
        Price
        Priority hi/md/lo
        -->
        <th class="sorter-digit" valign="middle">{% trans 'ID' %}</th>
        <th class="sorter-text" style="white-space: nowrap">{% trans 'Order name' %}</th>
        <th class="sorter-text">{% trans 'Assignment' %}</th>
        {% if action_label == 'all' %}
          <th class="sorter-text">{% trans 'Status' %}</th>
        {% endif %}
        <th class="sorter-text">{% trans 'Mark' %}</th>
        <th class="sorter-text">{% trans 'Site' %}</th>
        <th class="sorter-text">{% trans 'Owner' %}</th>
        <th class="sorter-text">{% trans 'Manager' %}</th>
        <th class="sorter-text">{% trans 'Writer' %}</th>
        <th class="sorter-text">{% trans 'Editor' %}</th>
        <th class="sorter-text">{% trans 'Customer timezone' %}</th>
        <th class="sorter-text">{% trans 'Created' %}</th>
        <!-- <th class="sorter-text">{% trans 'Updated' %}</th> -->
        <th class="sorter-text">{% trans 'Urgency' %}</th>
        <!--th class="sorter-text">{% trans 'Loc. time' %}</th-->
        <th class="sorter-text">{% trans 'Full DL' %}</th>
        <th class="sorter-text">{% trans 'Writer DL' %}</th>
        <th class="sorter-text">{% trans 'Access' %}</th>
        <th class="sorter-text">{% trans 'Revision' %}</th>
        <!-- <th class="sorter-text">{% trans 'Discount (%)' %}</th> -->
        <th class="sorter-text">{% trans 'Payment status' %}</th>
        <th class="sorter-text">{% trans 'Price / Discount' %}</th>
        <th class="sorter-text">{% trans 'Priority' %}</th>
    </tr>
</thead>
<tbody>
    {% for task in tasks %}
    <tr>
        <td>{{task.id}}</td>
        <td><a href="{% url 'task_view' task.id %}">{{task.paper_title}}</a></td>
        <td>{{task.get_assigment}}</td>
        {% if action_label == 'all' %}
          <td data-status="{{task.status}}" style="font-size:1.4em;line-height:100%">{{task.status|render_status}}</td>
        {% endif %}
        <td>{{task.mark}}</td>
        <td>{{task.site}}</td>
        <td>{% if task.owner %}<a href="{% url 'user_edit' task.owner.id %}">{{task.owner}}</a>{% endif  %}</td>
        <td>{% if task.manager %}<a href="{% url 'user_edit' task.manager.id %}">{{task.manager}}</a>{% endif  %}</td>
        <td>{% if task.assignee %}<a href="{% url 'user_edit' task.assignee.id %}">{{task.assignee}}</a>{% endif  %}</td>
        <td>{% if task.editor %}<a href="{% url 'user_edit' task.editor.id %}">{{task.editor}}</a>{% endif  %}</td>
        <td>{{task.owner.userprofile.timezone}}</td>
        <td>{{task.created}}</td>
        <td>{{task.get_urgency}}</td>
        <!--td>loc.time not implemented</td-->
        <td class="momdl">{{task.admin_deadline}}</td>
        <td class="momdl">{{task.writer_deadline}}</td>
        <td>{{task.get_access_level}}</td>
        <td>{{task.revision}}</td>
        <td>{{payments|get_order_status:task.pk}}</td>
        <td>{{task.get_price}}</td>
        <td>{{task.priority}}</td>
    </tr>
    {% endfor %}
</tbody>
<tfoot>
    <tr></tr>
</tfoot>

templates/tasks/customer-tasks.html
{% load i18n render_status %}
<thead>
    <tr>
        <th class="sorter-digit">{% trans 'ID' %}</th>
        <th class="sorter-text">{% trans 'Order name' %}</th>
        <th class="sorter-text">{% trans 'Assigment' %}</th>
        <th class="sorter-status">{% trans 'Status' %}</th>
        <th class="sorter-text">{% trans 'Writer' %}</th>
        <th>{% trans 'Created' %}</th>
        <th class="sorter-text">{% trans 'Urgency' %}</th>
        <th class="sorter-text">{% trans 'Deadline' %}</th>
        <th class="sorter-text">{% trans 'Revision' %}</th>
        <th class="sorter-text">{% trans 'Payment status' %}</th>
        <th class="sorter-text">{% trans 'Price' %}</th>
    </tr>
</thead>
<tbody>
    {% for task in tasks %}
    <tr>
        <td>{{task.id}}</td>
        <td><a href="{% url 'task_view' task.id %}">{{task.paper_title}}</a></td>
        <td>{{task.get_assigment}}</td>
        <td data-status="{% if task.status == co.SENT %}{{co.PROCESSING}}{% else %}{{task.status}}{% endif %}"
            style="font-size:1.4em;line-height:100%">
          {% if task.status == co.SENT %}{{co.PROCESSING|render_status}}{% else %}{{task.status|render_status}}{% endif %}
        </td>
        <td>{% if task.assignee %}{{task.assignee}}{% endif %}</td>
        <td>{{task.created}}</td>
        <td>{{task.get_urgency}}</td>
        <td class="momdl">{{task.admin_deadline}}</td>
        <td>{{task.review}}</td>
        <td></td>
        <td>{{task.get_price}}$</td>
    </tr>
    {% endfor %}
</tbody>
<tfoot>
    <tr></tr>
</tfoot>

templates/tasks/delete.html
{% extends "layout.html" %}
{% load i18n %}
{% block pagetitle %}{% trans "Task Details" %}{% endblock %}
{% block content %}
  <form action="{% url "task_remove" object.id %}" method="post">{% csrf_token %}
    <h3>{{object.title}}</h3>
    <div>Are you sure?</div>
    <input type="submit" value="Submit" />
  </form>
{% endblock %}
{% block info_block %}
<section class="info">
    <h2>{% trans "Task Details" %}</h2>
</section>
{% endblock %}

templates/tasks/edit.html
{% extends "layout.html" %}
{% load i18n attr %}
{% block pagetitle %}
  {% if object and object.status == co.DRAFT %}
    {% trans "Order Draft Edit" %}
  {% else  %}
    {% trans "Order Edit" %}
  {% endif %}
{% endblock %}
{% block content %}
<section class="container-fluid panel panel-default{% if form.errors %} panel-danger{% endif %}">
    <div class="panel-heading">
        <h3 class="panel-title">{% if object %}<i class="fa fa-edit fa-lg" style="margin-right:1em"></i>{% if object and object.status == co.DRAFT %}
          {% trans "Order Draft Edit" %}{% else %}{% trans "Order Edit" %}{% endif %} { Id: {{object.id}} }{% else %}<i class="fa fa-asterisk fa-lg" style="margin-right:1em"></i>{% trans "New Order" %}{% endif %}</h3>
    </div>
    <div class="panel-body">
        <form role="form" action="{% if object %}{% url "task_edit" object.pk %}{% else %}{% url "task_new" %}{% endif %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <!--
            {% if form.errors  %}
            {{form.errors}}
            {% endif  %}
            -->
            {% if site == "admin" or site == "editor" %}
            <div class="row">
                <div class="col-md-8">
                    {% endif %}
                    <div class="row">
                        <!-- pass some hidden fields to a customer -->
                        {% if site == 'customer' %}
                        <input type="hidden" name="access_level" value="{{co.PRIVATE_ACCESS}}">
                        {% endif %}
                        <!-- left column -->
                        <div class="{% if site == 'customer' or site == 'writer' %}col-md-5 col-md-offset-1{% else %}col-md-6{% endif %}">
                            <div class="form-group{% if form.assigment.errors %} has-error{% endif %}">
                                <label>{% trans "Assigment Type" %}</label>
                                <div class="input-group margin-bottom-sm">
                                    <span class="input-group-addon"><i class="fa fa-list-alt fa-fw"></i></span>
                                    {{form.assigment|attr:"class:form-control,autocomplete:off,placeholder:Assigment Type"}}
                                </div>
                            </div>
                            <div class="form-group{% if form.urgency.errors %} has-error{% endif %}">
                                <label>{% trans "Urgency" %}</label>
                                <div class="input-group margin-bottom-sm">
                                    <span class="input-group-addon"><i class="fa fa-clock-o fa-fw"></i></span>
                                    {{form.urgency|attr:"class:form-control,autocomplete:off,placeholder:Urgency"}}
                                </div>
                            </div>
                            <div class="form-group{% if form.page_number.errors %} has-error{% endif %}">
                                <label>{% trans "Number of pages" %}</label>
                                <div class="input-group margin-bottom-sm">
                                    <span class="input-group-addon"><i class="fa fa-files-o fa-fw"></i></span>
                                    {{form.page_number|attr:"class:form-control,autocomplete:off,placeholder:Number of pages"}}
                                </div>
                            </div>
                            <div class="form-group{% if form.spacing.errors %} has-error{% endif %}">
                                <label>{% trans "Spacing" %}</label>
                                <div class="input-group margin-bottom-sm">
                                    <span class="input-group-addon"><i class="fa fa-arrows-v fa-fw"></i></span>
                                    {{form.spacing|attr:"class:form-control,autocomplete:off,placeholder:Spacing"}}
                                </div>
                            </div>
                        </div>
                        <div class="{% if site == 'customer'%}col-md-5{% else %}col-md-6{% endif %}">
                            <div class="form-group{% if form.discipline.errors %} has-error{% endif %}">
                                <label>{% trans "Discipline" %}</label>
                                <div class="input-group margin-bottom-sm">
                                    <span class="input-group-addon"><i class="fa fa-book fa-fw"></i></span>
                                    {{form.discipline|attr:"class:form-control,autocomplete:off,placeholder:Discipline"}}
                                </div>
                            </div>
                            <div class="form-group{% if form.level.errors %} has-error{% endif %}">
                                <label>{% trans "Level" %}</label>
                                <div class="input-group margin-bottom-sm">
                                    <span class="input-group-addon"><i class="fa fa-certificate fa-fw"></i></span>
                                    {{form.level|attr:"class:form-control,autocomplete:off,placeholder:Level"}}
                                </div>
                            </div>
                            <div class="form-group{% if form.style.errors %} has-error{% endif %}">
                                <label>{% trans "Academic Styles" %}</label>
                                <div class="input-group margin-bottom-sm">
                                    <span class="input-group-addon"><i class="fa fa-building-o fa-fw"></i></span>
                                    {{form.style|attr:"class:form-control,autocomplete:off,placeholder:Styles"}}
                                </div>
                            </div>
                            <div class="form-group{% if form.source_number.errors %} has-error{% endif %}">
                                <label>{% trans "Number of sources/references" %}</label>
                                <div class="input-group margin-bottom-sm">
                                    <span class="input-group-addon"><i class="fa fa-bars fa-fw"></i></span>
                                    {{form.source_number|attr:"class:form-control,autocomplete:off,placeholder:Number of sources/references"}}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="{% if site == 'customer' or site == 'writer' %}col-md-10 col-md-offset-1{% else %}col-md-12{% endif %}">
                            {% if not object.pk %}
                            <div class="form-group{% if form.attach.errors %} has-error{% endif %}">
                                <div class="file-input form-control">
                                    <div class="input-group margin-bottom-sm">
                                        <span class="input-group-addon"><i class="fa fa-paperclip fa-fw"></i></span>
                                        <input id="id_attach" class="upload-file" type="file" title="Attachment" name="attach" required>
                                        {% if form.attach.value %}
                                        <a href="{{ MEDIA_URL }}{{ form.attach.value }}" style="margin:0 10px">{{ form.attach.value }}</a>
                                        <input id="attach-clear_id" type="checkbox" name="attach-clear" style="virtual-align:middle">
                                        <label for="attach-clear_id">{% trans "Delete" %}</label>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            {% endif  %}
                            <div class="form-group{% if form.paper_title.errors %} has-error{% endif %}">
                                <label>{% trans "Paper Title" %}</label>
                                <div class="input-group margin-bottom-sm">
                                    <span class="input-group-addon"><i class="fa fa-tag fa-fw"></i></span>
                                    {{form.paper_title|attr:"class:form-control,autocomplete:off,placeholder:Paper Title"}}
                                </div>
                            </div>
                            <div class="form-group{% if form.instructions.errors %} has-error{% endif %}">
                                <label>{% trans "Paper Instructions" %}</label>
                                {{form.instructions|attr:"class:form-control,rows:4,autocomplete:off,placeholder:Paper Instructions"}}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="{% if site == 'customer' or site == 'writer' %}col-md-5 col-md-offset-1{% else %}col-md-6{% endif %}">
                            <div class="form-group input-group margin-bottom-sm {% if form.accept_terms.errors %} has-error{% endif %}">
                                <span class="input-group-addon"> {{form.accept_terms|attr:"class:accept-chk"}} </span>
                                <span class="form-control" style="overflow:auto">{% trans "I accept terms and conditions" %}</span>
                            </div>
                            <div class="form-group input-group margin-bottom-sm">
                                <span class="input-group-addon"><i class="fa fa-barcode fa-fw"></i></span>
                                {{form.discount|attr:"class:form-control,autocomplete:off,placeholder:Discount Code"}}
                            </div>
                        </div>
                        <div class="form-group col-md-5" style="text-align:right;padding-top:1em">
                            {% if not object or perm.can_edit %}
                            <a href="#" class="btn-cancel btn btn-default btn-lg" data-back-to="/" role="button" style="width:40%"> <i class='fa fa-times-circle-o fa-lg' style="margin-right:.5em"></i>{% trans "Cancel" %} </a>
                            <button type="submit" class="btn btn-primary btn-lg" role="button" style="width:40%">
                                {% trans "Next" %}<i class='fa fa-check-circle-o fa-lg' style="margin-left:.5em"></i>
                            </button>
                            {% endif %}
                        </div>
                    </div>
                    {% if site == "admin" or site == "editor" %}
                </div>
                <div class="col-md-4">
                    <br>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Attributes
                        </div>
                        <div class="panel-body">
                            <div class="form-group{% if form.assignee.errors %} has-error{% endif %}">
                                <label>{% trans "Writer" %}</label>
                                <div class="input-group margin-bottom-sm">
                                    <span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
                                    {{form.assignee|attr:"class:form-control,autocomplete:off,placeholder:Writer"}}
                                </div>
                            </div>
                            <div class="form-group{% if form.mark.errors %} has-error{% endif %}">
                                <label>{% trans "Mark" %}</label>
                                <div class="input-group margin-bottom-sm">
                                    <span class="input-group-addon"><i class="fa fa-star-half-o fa-fw"></i></span>
                                    {{form.mark|attr:"class:form-control,autocomplete:off,placeholder:Mark"}}
                                </div>
                            </div>
                            {% if site == "admin" %}
                            <div class="form-group{% if form.access_level.errors %} has-error{% endif %}">
                                <label>{% trans "Access Level" %}</label>
                                <div class="input-group margin-bottom-sm">
                                    <span class="input-group-addon"><i class="fa fa-eye fa-fw"></i></span>
                                    {{form.access_level|attr:"class:form-control,autocomplete:off,placeholder:Access Level"}}
                                </div>
                            </div>
                            {% endif %}
                            <div class="form-group{% if form.priority.errors %} has-error{% endif %}">
                                <label>&nbsp;</label>
                                <div class="input-group margin-bottom-sm">
                                    <span class="input-group-addon"> {{form.priority|attr:"class:accept-chk"}} </span>
                                    <span class="form-control" style="overflow:auto;width:100%">{% trans "Priority" %}</span>
                                </div>
                            </div>
                            <div class="form-group{% if form.revision.errors %} has-error{% endif %}">
                                <label>&nbsp;</label>
                                <div class="input-group margin-bottom-sm">
                                    <span class="input-group-addon"> {{form.revision|attr:"class:accept-chk"}} </span>
                                    <span class="form-control" style="overflow:auto;width:100%">{% trans "Revision" %}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
        </form>
    </div>
</section>
{% endblock %}
{% block info_block %}
{% endblock %}

templates/tasks/editor-tasks.html
{% load i18n render_status %}
<thead>
    <tr>
        <!--
        id
        order name
        ass type
        status
        marks *****
        site (url)
        owner
        admin
        writer
        editor
        Local time
        Created
        Urgency
        Full Deadline
        Writer's deadline
        Updated
        Order type priv/public
        in review 1/0
        Discount (%)
        Payment status
        Price
        Priority hi/md/lo
        -->
        <th class="sorter-digit">{% trans 'ID' %}</th>
        <th class="sorter-text" style="white-space: nowrap">{% trans 'Order name' %}</th>
        <!-- <th class="sorter-text">{% trans 'Status' %}</th> -->
        <th class="sorter-text">{% trans 'Assignment' %}</th>
        <th class="sorter-text">{% trans 'Mark' %}</th>
        <th class="sorter-text">{% trans 'Writer' %}</th>
        <th class="sorter-text">{% trans 'Editor' %}</th>
        <th class="sorter-text">{% trans 'Customer Timezone' %}</th>
        <th class="sorter-text">{% trans 'Created' %}</th>
        <!-- <th class="sorter-text">{% trans 'Updated' %}</th> -->
        <th class="sorter-text">{% trans 'Urgency' %}</th>
        <!--th class="sorter-text">{% trans 'Loc. time' %}</th -->
        <th class="sorter-text">{% trans 'Full DL' %}</th>
        <th class="sorter-text">{% trans 'Writer DL' %}</th>
        <th class="sorter-text">{% trans 'Revision' %}</th>
        <!-- <th class="sorter-text">{% trans 'Discount (%)' %}</th> -->
        <th class="sorter-text">{% trans 'Priority' %}</th>
    </tr>
</thead>
<tbody>
    {% for task in tasks %}
    <tr>
        <td>{{task.id}}</td>
        <td><a href="{% url 'task_view' task.id %}">{{task.paper_title}}</a></td>
        <!-- <td>{{task.status|render_status}} - {{task.status}}</td> -->
        <td>{{task.get_assigment}}</td>
        <td>{{task.mark}}</td>
        <td>{% if task.assignee %}<a href="{% url 'user_details' task.assignee.id %}">{{task.assignee}}</a>{% endif %}</td>
        <td>{% if task.editor %}<a href="{% url 'user_details' task.editor.id %}">{{task.editor}}</a>{% endif %}</td>
        <td>{{task.owner.userprofile.timezone}}</td>
        <td>{{task.created}}</td>
        <td>{{task.get_urgency}}</td>
        <!--td>loc.time not implemented</td-->
        <td class="momdl">{{task.admin_deadline}}</td>
        <td class="momdl">{{task.writer_deadline}}</td>
        <td>{{task.revision}}</td>
        <td>{{task.priority}}</td>
    </tr>
    {% endfor %}
</tbody>
<tfoot>
    <tr></tr>
</tfoot>

templates/tasks/index.html
{% extends "layout.html" %}
{% load i18n %}
{% block pagetitle %}Tasks{% endblock %}
{% block info_block %}
<section class="info">
    <h2><i class="fa fa-tasks irm"></i> {% trans "Tasks List" %} <small style="color:#333;margin-left:0.5em">{{action_label}} <sup><span class="badge" style="font-size:.6em;text-shadow:none;margin-left:.5em;background-color:#08F">{{tasks|length}}</span></sup></small></h2>
</section>
{% endblock %}
{% block content %}
{% if tasks %}
<div class="row">
    {{ PATH_IFNO }}
    <div class="col-md-12">
        <table class="tablesorter tablesorter-default table table-hover table-condensed">
            {% with "tasks/"|add:site|add:"-tasks.html" as template %}
            {% include template %}
            {% endwith %}
        </table>
    </div>
</div>
{% endif  %}
{% endblock %}
{% block styles %}
<link rel="stylesheet" href="{{ STATIC_URL }}css/theme.default.css" type="text/css">
{% endblock %}

templates/tasks/taskstree_list.html
<h1>Tasks</h1>
<ul>
{% for task in object_list %}
    <li>{{ task.name }}</li>
{% empty %}
    <li>No tasks yet.</li>
{% endfor %}
</ul>

templates/tasks/uploads_list.html
<table class="table table-hover table-condensed small" style="background-color:#fff;">
    <caption class="my">
        Uploads <span class="badge pull-right" style="margin-right:8px;background-color:#555">{{uploads|length}}</span>
    </caption>
    <thead>
        <tr>
            <th>File</th>
            <th>Owner</th>
            <th>Created/Updated</th>
            {% if perm.can_ch_visibility %}
              <th>&nbsp;</th>
            {% endif %}
            {% if perm.can_rm_upload %}
              <th>&nbsp;</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        {% for u in uploads  %}
        <tr>
            <td><a href="{% url "upload_download" u.pk %}">{{u.get_filename}}</a></td>
            <td><a href="{% url "user_details" u.fowner.pk %}">{{u.fowner}}</a></td>
            <td>
            <div>
                {{u.created}}
            </div>
            <div>
                {{u.updated}}
            </div></td>
            {% if perm.can_ch_visibility %}
            <td><a href="javascript:void()" data-url="{% url "upload_visibility" u.pk %}" class="set-public" style="font-size:1.5em"><i class="fa fa-eye{% if u.access_level == co.PRIVATE_ACCESS %}-slash text-danger{% endif %}"></i></a></td>
            {% endif %}
            {% if perm.can_rm_upload %}
            <td><a href="javascript:void()" data-file-name="{{u.attach.name}}" data-url="{% url "upload_remove" u.pk %}" class="upload-delete"  style="font-size:1.5em;color:#a00"><i class="fa fa-times-circle"></i></a></td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
    <tfoot class="my">
        <tr></tr>
    </tfoot>
</table>

templates/tasks/writer-tasks.html
{% load i18n  render_status %}
<thead>
    <tr>
        <th class="sorter-digit">{% trans 'ID' %}</th>
        <th>{% trans 'Order name' %}</th>
        <th>{% trans 'Assigment' %}</th>
        <th class="sorter-status">{% trans 'Status' %}</th>
        <th>{% trans 'Mark' %}</th>
        <th>{% trans 'Deadline' %}</th>
        <th>{% trans 'Revision' %}</th>
        <th>{% trans 'Price' %}</th>
    </tr>
</thead>
<tbody>
    {% for task in tasks %}
    <tr>
        <td>{{task.id}}</td>
        <td><a href="{% url 'task_view' task.id %}">{{task.paper_title}}</a></td>
        <td>{{task.get_assigment}}</td>
        <td data-status="{{task.status}}" style="font-size:1.4em;line-height:100%">{{task.status|render_status}}</td>
        <td>{{task.mark}}</td>
        <td class="momdl">{{task.writer_deadline}}</td>
        <td>{{task.revision}}</td>
        <td>{{task.get_writer_price }}</td>
    </tr>
    {% endfor %}
</tbody>
<tfoot>
    <tr></tr>
</tfoot>